### ISSUE TITLE
Muse engine optimization

### ISSUE THREAD

**Issue by Iamdavidonuh** [derhnyel/getmusic#1]
@derhnyel 

- You already handled the special case, which is `if child` remove this else statement, to deindent the function

https://github.com/derhnyel/Muse/blob/d77c47d3d075f3ac66441d72dba78e93310ec202/root.py#L62

**Comment by derhnyel** [comment]
@Iamdavidonuh  Please look into the engine optimization. apparently the engine should be able to handle both post and get requests with payloads.

**Comment by derhnyel** [comment]
The justnaija and songlovers engine would have  both fetch and search classes. Looking for a what to couple those together

**Comment by Iamdavidonuh** [comment]
> @Iamdavidonuh Please look into the engine optimization. apparently the engine should be able to handle both post and get requests with payloads.

weldone boss
